#!/bin/sh

# Определение директории, где находится xkeen.sh
# Добавляю декларии для удобной работы в VSCODE + плагин "BASH IDE", Clion + "Shell Script" от компаниии JetBrains, потом раскоментировать
#script_dir="$(cd "$(dirname "$0")" && pwd)"

# Блок для удаления
# Integration with external tools (ShellCheck, Shfmt, Explainshell)
script_dir=./

# Модуль информации
. _xkeen/01_info/03_info_cpu.sh
. _xkeen/01_info/05_info_geosite.sh




# Скрываем основную директорию xkeen
install_xkeen_rename() {
    script_dir="$script_dir"
    source_dir="_xkeen"
    target_dir=".xkeen"
    source_path="$script_dir/$source_dir"
    target_path="$script_dir/$target_dir"
    
    if [ -d "$source_path" ]; then
        if [ -d "$target_path" ]; then
            rm -rf "$target_path" 2>/dev/null
        fi
        mv "$source_path" "$target_path"
    fi
	rm /opt/root/install.sh 2>/dev/null
}
install_xkeen_rename

add_chmod_init() {
		chmod +x $initd_dir/S24xray
		chmod 755 $initd_dir/S24xray	
		chmod +x $initd_dir/S99xkeenstart
		chmod 755 $initd_dir/S99xkeenstart
}

# Импортируем модули
. "$script_dir/.xkeen/import.sh"

# Очищаем журнал перед работой
	logs_clear
	
xkeen_info() {
	eval "opkg update &>/dev/null"
	eval "opkg upgrade &>/dev/null"
    # Проверяем установку пакетов
    info_packages
    logs_packages_info_xkeen
	
    # Собираем необходимую информацию о процессоре
    info_cpu
    logs_cpu_info_xkeen	

    # Проверяем установку xray
    info_xray
    logs_xray_info_xkeen

    # Проверяем установленные базы geosite
    info_geosite
    logs_geosite_info_xkeen

    # Проверяем установленные базы geoip
    info_geoip
    logs_geoip_info_xkeen

    # Проверяем статусы автоматических обновлений
    info_cron
    logs_cron_info_xkeen

    # Проверяем версию xkeen
    info_version_xkeen
    logs_version_xkeen_info_xkeen

    # Проверяем актуальность xkeen
    info_compare_xkeen
    logs_compare_xkeen_info_xkeen
	
    # Проверяем версию xray
    info_version_xray
    logs_version_xray_info_xkeen

    # Проверяем актуальность xray
    info_compare_xray
    logs_compare_xray_info_xkeen

    # Устанавливаем недостающие пакеты
    install_packages
    logs_install_packages_xkeen
}


	
while [ $# -gt 0 ]; do
    case "$1" in
	
        -i)	# Запуск полного цикла установки
			# Устанавливаем xray			
			clear
			echo "  Запуск полного цикла установки"
			xkeen_info
			logs_cpu_info_console
			if [ -z "$architecture" ]; then
				exit 1
			fi	

				if [ "$xray_installed" = "not_installed" ]; then
					echo ""
					download_xray
					logs_download_xray_info_xkeen
					
					install_xray
					
					xray_installed="installed"
					info_version_xray
				fi
			
			# Обновляем xray	
				if [ "$info_compare_xray" = "update" ]; then
					echo ""
					download_xray
					logs_download_xray_info_xkeen
					
					install_xray
					
					info_compare_xray="actual"
					info_version_xray
				fi
			sleep 2
			clear

			# Устанавливаем geosite
				choose_geosite
				logs_choose_geosite_info_xkeen
				
				delete_geosite
					logs_delete_geosite_info_xkeen
										
					install_geosite
					logs_install_geosite_info_xkeen
			sleep 2
			clear
				
			# Устанавливаем geoip
				choose_geoip
				logs_choose_geoip_info_xkeen
				
					delete_geoip
					logs_delete_geoip_info_xkeen
					
					install_geoip
					logs_install_geoip_info_xkeen
			sleep 2
			clear

			# Настраиваем автоматические обновления
				update_cron_geofile_task
				choose_update_cron
				logs_choose_update_cron_info_xkeen
			clear
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
					delete_cron_task
					logs_delete_cron_task_info_xkeen
					
					install_cron
					logs_install_cron_info_xkeen
			sleep 2
			clear

			# Удаляем предыдущие регистрации
				delete_register_xkeen
				logs_delete_register_xkeen_info_xkeen
								
				delete_register_xray
				logs_delete_register_xray_info_xkeen
				
				install_configs
				logs_install_configs_info_xkeen
								
				register_xray_list
				logs_register_xray_list_info_xkeen
				
				register_xray_control
				logs_register_xray_control_info_xkeen
				
				register_xray_status
				logs_register_xray_status_info_xkeen
				
				register_xray_initd
                                register_autostart
				
			# Регистрируем xkeen
				register_xkeen_list
				logs_register_xray_list_info_xkeen
				
				register_xkeen_control
				logs_register_xray_control_info_xkeen
				
				register_xkeen_status
				logs_register_xkeen_status_info_xkeen

			# Создаем init для cron
				echo ""
				eval "/opt/etc/init.d/S05crond stop" 2>/dev/null
				[ -e "$initd_dir/S05crond" ] && rm -f "$initd_dir/S05crond"
				
				register_cron_initd
				
				eval "/opt/etc/init.d/S05crond start" 2>/dev/null
				
			# Исправление регистраций
				fixed_register_packages

			# Удаляем временные файлы
				echo ""
				delete_tmp
				logs_delete_tmp_info_xkeen
                        	rm -f "$install_dir/xray_bak"
				rm -rf "$xtmp_dir"

				sleep 2
				clear
				echo ""
				echo -e "  ${green}Установка завершена!${reset}"
				echo ""
				echo -e "  Настройте конфигурацию Xray по пути «${yellow}/opt/etc/xray/configs/${reset}»"
				echo -e "  и запустите XKeen командой ${yellow}xkeen -start${reset}"
				echo ""
				echo -e "  Для вывода Справки выполните ${yellow}xkeen -h${reset}"
            shift
            ;;

        -ug)	#Запуск обновления баз GeoFile	
			echo "  Обновление установленных GeoFile"
			sleep 2
			while [ -f "/opt/tmp/gueue" ]; do
			    sleep 10
			done
                        touch "/opt/tmp/queue"

			info_geosite
			logs_geosite_info_xkeen
			
			if [ "$geo_exists_geosite_v2fly" = "installed" ]; then
				install_v2fly_geosite="true"
            fi
			
			if [ "$geo_exists_geosite_antifilter" = "installed" ]; then
			install_antifilter_geosite="true"
            fi
						
			if [ "$geo_exists_geosite_zkeen" = "installed" ]; then
				install_zkeen_geosite="true"
            fi
				
				install_geosite
				#logs_install_geosite_info_xkeen
				#logs_install_geosite_info_console
			
			info_geoip
			logs_geoip_info_xkeen
			
			if [ "$geo_exists_geoip_v2fly" = "installed" ]; then
				install_v2fly_geoip="true"
            fi
			
			if [ "$geo_exists_geoip_antifilter" = "installed" ]; then
                		install_antifilter_geoip="true"
            fi

			if [ "$geo_exists_geoip_zkeenip" = "installed" ]; then
                		install_zkeenip_geoip="true"
            fi
				
				install_geoip
				#logs_install_geoip_info_xkeen
				#logs_install_geoip_info_console

			# eval "/opt/etc/init.d/S24xray restart"
                        "/opt/etc/init.d/S24xray restart on" 2>/dev/null

			echo "  Обновление установленных GeoSite завершено"
			rm -f "/opt/tmp/queue"
            shift
            ;;
			
        -uk)		#Запуск обновления XKeen
			echo "  Проверка обновлений XKeen"
			touch "/opt/tmp/queue"

			xkeen_info
			
				if [ "$info_compare_xkeen" = "update" ]; then
					clear
					echo -e "  Найдена новая версия ${yellow}XKeen${reset}"	
					backup_xkeen
					
					download_xkeen
					logs_download_xkeen_info_xkeen
					
					install_xkeen

					echo -e "  ${yellow}Выполняется${reset} отмена регистрации старой версии XKeen"
					delete_register_xkeen
					logs_delete_register_xkeen_info_xkeen
					logs_delete_register_xkeen_info_console

					sleep 1	
					echo -e "  ${yellow}Выполняется${reset} регистрация новой версии XKeen"
				
					register_xkeen_list
					logs_register_xkeen_list_info_xkeen
					logs_register_xkeen_list_info_console
					
					register_xkeen_control
					logs_register_xkeen_control_info_xkeen
					logs_register_xkeen_control_info_console
					
					register_xkeen_status
					logs_register_xkeen_status_info_xkeen
					logs_register_xkeen_status_info_console
					
					register_cron_initd
					register_xray_initd
                                        register_autostart
					update_cron_geofile_task

					fixed_register_packages
					delete_tmp
					logs_delete_tmp_info_xkeen
					echo -e "  Обновление XKeen ${green}завершено${reset}"
				else
					echo "  Нет доступных обновлений XKeen"
				fi
			rm -f "/opt/tmp/queue"
            shift
            ;;
						
        -ux)		#Запуск обновления Xray
			echo "  Проверка обновлений Xray"

			sleep 5
			while [ -f "/opt/tmp/gueue" ]; do
			    sleep 10
			done
			touch "/opt/tmp/queue"

			xkeen_info
			
				if [ "$info_compare_xray" = "update" ]; then
					clear
					echo ""
					echo -e "  Найдена новая версия ${yellow}Xray${reset}"
					echo -e "  Подготовка к обновлению"
					#eval "/opt/etc/init.d/S24xray stop" 2>/dev/null
					#[ -e "$initd_dir/S24Xray" ] && rm -f "$initd_dir/S24Xray"

					download_xray
					logs_download_xray_info_xkeen

					install_xray

					echo -e "  ${yellow}Выполняется${reset} отмена регистрации старой версии Xray"

					delete_register_xray
					logs_delete_register_xray_info_xkeen
					logs_delete_register_xray_info_console

					sleep 1
					echo -e "  ${yellow}Выполняется${reset} регистрация новой версии Xray"

					register_xray_list
					logs_register_xray_list_info_xkeen
					logs_register_xray_list_info_console

					register_xray_control
					logs_register_xray_control_info_xkeen
					logs_register_xray_control_info_console

					register_xray_status
					logs_register_xray_status_info_xkeen
					logs_register_xray_status_info_console

					#register_xray_initd
                                        #register_autostart
					#logs_register_xray_initd_info_xkeen
					#logs_register_xray_initd_info_console

					sleep 2

					#eval "/opt/etc/init.d/S24xray restart" 2>/dev/null
					"/opt/etc/init.d/S24xray restart on" 2>/dev/null

					#delete_tmp
					#logs_delete_tmp_info_xkeen

					echo ""
					echo -e "  Обновление Xray ${green}завершено${reset}"
					echo ""
				else
					echo "  Нет доступных обновлений Xray"
				fi
                        rm -f "$install_dir/xray_bak"
			rm -f "/opt/tmp/queue"
			rm -rf "$xtmp_dir"
            shift
            ;;

		-uac)	#Создать или изменить существующие правила автоматического обновления GeoFile, XKeen, Xray	
				echo "  Создание или изменение правил автоматического обновления GeoFile, XKeen, Xray"
				info_cron
				logs_cron_info_xkeen
				
				clear
				delete_cron_geofile 2>/dev/null
				delete_cron_xkeen 2>/dev/null
				delete_cron_xray 2>/dev/null

                    chose_geofile_cron_select=true
                    chose_xkeen_cron_select=true
                    chose_xray_cron_select=true

				if input_concordance_list "Хотите установить единое время для ${yellow}всех${reset} обновлений?"; then
                        chose_all_cron_select=true
                        chose_geofile_cron_select=false
                        chose_xkeen_cron_select=false
                        chose_xray_cron_select=false
                    else
                        chose_all_cron_select=false
				fi
					
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
				install_cron
				logs_install_cron_info_xkeen
				logs_install_cron_info_console
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				echo "  Создание или изменение правил автоматического обновления GeoFile, XKeen, Xray завершено"
				
            shift
            ;;
			
			
		-ukc)	#Создать или изменить существующее правило автоматического обновления XKeen
				echo "  Создание или изменение правила автоматического обновления XKeen"
				info_cron
				logs_cron_info_xkeen
				
				clear
				delete_cron_xkeen
				logs_delete_cron_xkeen_info_xkeen
				
				chose_xkeen_cron_select=true
				
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
				install_cron
				logs_install_cron_info_xkeen
				logs_install_cron_info_console
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				echo "  Создание или изменение правила автоматического обновления XKeen завершено"
            shift
            ;;
			
			
		-uxc)	#Создать или изменить существующее правило автоматического обновления Xray
				echo "  Создание или изменение правила автоматического обновления Xray"
				info_cron
				logs_cron_info_xkeen
				
				clear
				delete_cron_xray
				logs_delete_cron_xray_info_xkeen
				
				chose_xray_cron_select=true
				
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
				install_cron
				logs_install_cron_info_xkeen
				logs_install_cron_info_console
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				
				echo "  Создание или изменение правила автоматического обновления Xray завершено"
            shift
            ;;
			
			
		-ugc)	#Создать или изменить существующее правило автоматического обновления GeoFile
				echo "  Создание или изменение правила автоматического обновления GeoFile"
				info_cron
				logs_cron_info_xkeen
				
				clear
				delete_cron_geofile
				logs_delete_cron_geofile_info_xkeen
				
				chose_geofile_cron_select=true
				
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
				install_cron
				logs_install_cron_info_xkeen
				logs_install_cron_info_console
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				
				echo "  Создание или изменение правила автоматического обновления GeoFile завершено"
            shift
            ;;

		-rx)	#Зарегистрировать Xray
				xkeen_info
				echo "  Регистрация Xray в системе"
				clear
				echo -e "  Прегистрация ${yellow}Xray${reset}"	
				delete_register_xray
				logs_delete_register_xray_info_xkeen
				logs_delete_register_xray_info_console
				
				echo -e "  ${yellow}Выполняется${reset} регистрация"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset}"
				
				register_xray_list
				logs_register_xray_list_info_xkeen
				logs_register_xray_list_info_console
				
				register_xray_control
				logs_register_xray_control_info_xkeen
				logs_register_xray_control_info_console
				
				register_xray_status
				logs_register_xray_status_info_xkeen
				logs_register_xray_status_info_console
				fixed_register_packages
				
				echo ""
				echo -e "  Проверка регистрации ${green}завершена${reset}"
				
				echo "  Регистрация Xray в системе завершена"								
            shift
            ;;
			

		-ri)	#Создать правило автоматического запуска Xray
				echo "  Создание правила автоматического запуска Xray"
				clear
				eval "/opt/etc/init.d/S24xray stop" 2>/dev/null
				[ -e "$initd_dir/S24Xray" ] && rm -f "$initd_dir/S24Xray"
				
				echo -e "  Создание файла автоматического запуска ${yellow}Xray${reset}"	
				sleep 1
				
				register_xray_initd
                                register_autostart
				logs_register_xray_initd_info_xkeen
				
				echo ""
				echo -e "  ${yellow}Проверка${reset} init.d"
				logs_register_xray_initd_info_console
				
				echo ""
				echo -e "  Если Ваша конфигурация Xray готова, то можете запустить его «${green}xkeen -start${reset}»"
				
				echo "  Создание правила автоматического запуска Xray завершено"
            shift
            ;;


		-rk)	#Зарегистрировать XKeen
				xkeen_info			
				clear
				echo -e "  Регистрация ${yellow}XKeen${reset}"	
		
				delete_register_xkeen
				logs_delete_register_xkeen_info_xkeen
				logs_delete_register_xkeen_info_console
				
				echo -e "  ${yellow}Выполняется${reset} регистрация"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset} регистрации"
				
				register_xkeen_list
				logs_register_xkeen_list_info_xkeen
				logs_register_xkeen_list_info_console
				
				register_xkeen_control
				logs_register_xkeen_control_info_xkeen
				logs_register_xkeen_control_info_console
				
				register_xkeen_status
				logs_register_xkeen_status_info_xkeen
				logs_register_xkeen_status_info_console
				
				fixed_register_packages
				
				echo ""
				echo -e "  Проверка регистрации ${green}завершена${reset}"
				
				echo "  Регистрация XKeen в системе завершена"	
            shift
            ;;


		-dac)	#Удалить правила автоматического обновления GeoFile, XKeen, Xray

				info_cron
				logs_cron_info_xkeen
				
				clear
				echo -e "  Удаление задач автоматического обновления ${yellow}GeoFile${reset}, ${yellow}XKeen${reset}, ${yellow}Xray${reset}"

				delete_cron_geofile
				logs_delete_cron_geofile_info_xkeen
				logs_delete_cron_geofile_info_console

				delete_cron_xkeen
				logs_delete_cron_xkeen_info_xkeen
				logs_delete_cron_xkeen_info_console
				
				delete_cron_xray
				logs_delete_cron_xray_info_xkeen
				logs_delete_cron_xray_info_console

				echo ""
				delete_tmp
				logs_delete_tmp_info_xkeen
				echo -e "  Удаление правил автоматического обновления GeoFile, XKeen, Xray ${green}завершено${reset}"
            shift
            ;;
			
			
		-dkc)		#Удалить правило автоматического обновления XKeen
				echo "  Удаление правила автоматического обновления XKeen"
				info_cron
				logs_cron_info_xkeen
				
				clear
				echo -e "  Удаление задачи автоматического обновления ${yellow}XKeen${reset}"	
				echo ""
				echo -e "  ${yellow}Проверка${reset} удаления задачи Cron для XKeen"
		
				delete_cron_xkeen
				logs_delete_cron_xkeen_info_xkeen
				logs_delete_cron_xkeen_info_console
				
				echo -e "  Проверка удаления задачи Cron для XKeen ${green}завершена${reset}"
				echo ""
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				
				echo "  Удаление правила автоматического обновления XKeen завершено"
            shift
            ;;
			

		-dxc)		#Удалить правило автоматического обновления Xray
				echo "  Удаление правила автоматического обновления Xray"
				info_cron
				logs_cron_info_xkeen
				
				clear
				echo -e "  Удаление задачи автоматического обновления ${yellow}Xray${reset}"	
				echo ""
				echo -e "  ${yellow}Проверка${reset} удаления задач Cron для Xray"
		
				delete_cron_xray
				logs_delete_cron_xray_info_xkeen
				logs_delete_cron_xray_info_console
				
				echo -e "  Проверка удаления задачи Cron для Xray ${green}завершена${reset}"
				echo ""
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				
				echo "  Удаление правила автоматического обновления Xray завершено"
            shift
            ;;
			

		-dgc)		#Удалить правило автоматического обновления GeoFile
				echo "  Удаление правила автоматического обновления GeoFile"
				info_cron
				logs_cron_info_xkeen
				
				clear
				echo -e "  Удаление задачи автоматического обновления ${yellow}GeoFile${reset}"	
				echo ""
				echo -e "  ${yellow}Проверка${reset} удаления задач Cron для GeoFile"
				
				delete_cron_geofile
				logs_delete_cron_geofile_info_xkeen
				logs_delete_cron_geofile_info_console
				
				echo -e "  Проверка удаления задачи Cron для GeoFile ${green}завершена${reset}"
				echo ""
				
				delete_tmp
				logs_delete_tmp_info_xkeen
				
				echo "  Удаление правила автоматического обновления GeoFile завершено"
            shift
            ;;


		-dx)	#Удалить Xray
				echo -e "  ${yellow}Удаление${reset} Xray"	
				
				eval "/opt/etc/init.d/S24xray stop" 2>/dev/null
				eval "opkg remove xray_s"

				echo ""
				echo -e "  Удаление Xray ${green}завершено${reset}"
				sleep 2
            shift
            ;;
			
			
		-dk)	#Удалить XKeen
				clear
				echo -e "  Удаление ${yellow}XKeen${reset}"	
				eval "opkg remove xkeen"
				delete_tmp
                                #if [ -d "/opt/backups" ]; then
                                #    rm -r "/opt/backups"
                                #fi

				echo ""
				echo -e "  Удаление XKeen ${green}завершено${reset}"
				echo -e "  Директорию резервных копий ${yellow}/opt/backups${reset} удалите вручную"
				echo ""
				echo -e "  Установить ${yellow}XKeen${reset} заново можно командами:"
				echo ""
				echo -e "  ${green}curl -sOfL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
				echo -e "  ${green}chmod +x ./install.sh${reset}"
				echo -e "  ${green}./install.sh${reset}"
            shift
            ;;


		-dgi)	#Удалить GeoIP's
				echo -e "  Удаление всех баз ${yellow}GeoIP${reset}"	

				delete_geoip_key
				logs_delete_geoip_info_xkeen
				logs_delete_geoip_info_console

				echo ""				
				echo -e "  Удаление всех баз GeoIP ${green}завершено${reset}"
            shift
            ;;
			
			
		-dgs)	#Удалить GeoSite's
				echo -e "  Удаление всех баз ${yellow}GeoSite${reset}"	

				delete_geosite_key
				logs_delete_geosite_info_xkeen
				logs_delete_geosite_info_console
		
				echo ""				
				echo -e "  Удаление всех баз GeoSite ${green}завершено${reset}"
            shift
            ;;
			
			
		-dt)	#Удалить временные файлы XKeen
				delete_tmp
				logs_delete_tmp_info_xkeen
            shift
            ;;
			
			
		-dc)	#Удалить все конфиги Xray
				echo -e "  Удаление ${yellow}конфигурационных файлов Xray${reset}"	

				delete_configs
				logs_delete_configs_info_console
				logs_delete_configs_info_xkeen				

				echo ""				
				echo -e "  Удаление всех конфигурационных файлов Xray ${green}завершено${reset}"
            shift
            ;;
			
			
		-drx)	#Удалить регистрации Xray
				echo "  Удаление регистрации Xray из системы"
				
				clear
				echo -e "  Удаление ${yellow}регистрации Xray${reset}"	
				echo ""
				sleep 1
				echo -e "  ${yellow}Проверка${reset} удаления регистрации Xray"
				
				delete_register_xray
				logs_delete_register_xray_info_xkeen
				logs_delete_register_xray_info_console
				
				echo -e "  Проверка удаления регистрации Xray ${green}выполнена${reset}"
				
				echo "  Удаление регистрации Xray из системы завершено"
            shift
            ;;
			

		-drk)	#Удалить регистрации XKeen
				echo "  Удаление регистрации XKeen из системы"
				
				clear
				echo -e "  Удаление ${yellow}регистрации XKeen${reset}"	
				echo ""
				sleep 1
				echo -e "  ${yellow}Проверка${reset} удаления регистрации XKeen"
				
				delete_register_xkeen
				logs_delete_register_xkeen_info_xkeen
				logs_delete_register_xkeen_info_console
				
				echo -e "  Проверка удаления регистрации XKeen ${green}выполнена${reset}"
				
				echo "  Удаление регистрации XKeen из системы завершено"
            shift
            ;;


		-remove)	# Полная деинсталляция XKeen и всех зависимостей
				# Удаление правил автоматического обновления GeoFile, XKeen, Xray

				info_cron
				logs_cron_info_xkeen
				
				clear
				echo -e "  Удаление задач автоматического обновления ${yellow}GeoSite${reset}, ${yellow}XKeen${reset}, ${yellow}Xray${reset}"
				delete_cron_geofile
				logs_delete_cron_geofile_info_xkeen
				logs_delete_cron_geofile_info_console

				delete_cron_xkeen
				logs_delete_cron_xkeen_info_xkeen
				logs_delete_cron_xkeen_info_console
				
				delete_cron_xray
				logs_delete_cron_xray_info_xkeen
				logs_delete_cron_xray_info_console

				echo ""
				echo -e "  Удаление правил автоматического обновления GeoFile, XKeen, Xray ${green}завершено${reset}"
				sleep 2

				#Удаление GeoIP's
				clear
				echo -e "  Удаление всех баз ${yellow}GeoIP${reset}"	

				delete_geoip_key
				logs_delete_geoip_info_xkeen
				logs_delete_geoip_info_console

				echo ""				
				echo -e "  Удаление всех баз GeoIP ${green}завершено${reset}"
				sleep 2

				#Удаление GeoSite's
				clear
				echo -e "  Удаление всех баз ${yellow}GeoSite${reset}"	

				delete_geosite_key
				logs_delete_geosite_info_xkeen
				logs_delete_geosite_info_console
		
				echo ""				
				echo -e "  Удаление всех баз GeoSite ${green}завершено${reset}"
				sleep 2

				#Удаление файлов конфигурации Xray
				clear
				echo -e "  Удаление ${yellow}конфигурационных файлов Xray${reset}"	

				delete_configs
				logs_delete_configs_info_console
				logs_delete_configs_info_xkeen				

				echo ""				
				echo -e "  Удаление всех конфигурационных файлов Xray ${green}завершено${reset}"
				sleep 2

				#Удаление Xray
				clear
				echo -e "  ${yellow}Удаление${reset} Xray"	
				
				eval "/opt/etc/init.d/S24xray stop" 2>/dev/null
				eval "opkg remove xray_s"

				echo ""
				echo -e "  Удаление Xray ${green}завершено${reset}"
				sleep 2

				#Удаление XKeen
				clear
				echo -e "  Удаление ${yellow}XKeen${reset}"	
				eval "opkg remove xkeen"
				delete_tmp

                                #if [ -d "/opt/backups" ]; then
                                #    rm -r "/opt/backups"
                                #fi

				echo ""
				echo -e "  Удаление XKeen ${green}завершено${reset}"
				sleep 2

				clear
				echo ""
				echo -e "  Полная деинсталляция ${yellow}XKeen${reset} и всех зависимостей ${green}выполнена${reset}"
				echo -e "  Директорию резервных копий ${yellow}/opt/backups${reset} удалите вручную"
				echo ""
				echo -e "  Рекомендуется ${green}перезагрузить роутер${reset}"
				echo ""
				echo -e "  Установить ${yellow}XKeen${reset} заново можно командами:"
				echo ""
				echo -e "  ${green}curl -sOfL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
				echo -e "  ${green}chmod +x ./install.sh${reset}"
				echo -e "  ${green}./install.sh${reset}"

            shift
            ;;


		-rrk)	#Обновить регистрацию XKeen
				echo "  Обновление регистрации XKeen в системе"
				
				clear
				echo -e "  Обновление регистрации ${yellow}XKeen${reset}"	
				
				info_cpu
				logs_cpu_info_xkeen
				info_version_xkeen
				logs_version_xkeen_info_xkeen
				
				delete_register_xkeen				
				logs_delete_register_xkeen_info_xkeen
				logs_delete_register_xkeen_info_console
				
				echo -e "  ${yellow}Выполняется${reset} обновление регистрации"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset} регистрации"
				
				register_xkeen_list
				logs_register_xkeen_list_info_xkeen
				logs_register_xkeen_list_info_console
				
				register_xkeen_control
				logs_register_xkeen_control_info_xkeen
				logs_register_xkeen_control_info_console
				
				register_xkeen_status
				logs_register_xkeen_status_info_xkeen
				logs_register_xkeen_status_info_console
				
				echo ""
				echo -e "  Проверка регистрации ${green}завершена${reset}"
				
				echo "  Обновление регистрации XKeen в системе завершено"
            shift
            ;;
			
			
		-rrx)	#Обновить регистрацию Xray
				echo "  Обновление регистрации Xray в системе"
				
				clear
				echo -e "  Обновление регистрации ${yellow}Xray${reset}"	
				
				info_xray
				logs_xray_info_xkeen
				info_cpu
				logs_cpu_info_xkeen
				info_version_xray
				logs_version_xray_info_xkeen
				
				delete_register_xray
				logs_delete_register_xray_info_xkeen
				logs_delete_register_xray_info_console
				
				echo -e "  ${yellow}Выполняется${reset} обновление регистрации"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset}"
			
				register_xray_list
				logs_register_xray_list_info_xkeen
				logs_register_xray_list_info_console
				
				register_xray_control
				logs_register_xray_control_info_xkeen
				logs_register_xray_control_info_console
				
				register_xray_status
				logs_register_xray_status_info_xkeen
				logs_register_xray_status_info_console
				
				echo ""
				echo -e "  Проверка регистрации ${green}завершена${reset}"
				
				echo "  Обновление регистрации Xray в системе завершено"
            shift
            ;;
				
			
		-rc)	#Переустановить конфиги Xray
				echo "  Переустановка конфигураций Xray"
				
				clear
				echo -e "  Переустановка конфигураций ${yellow}Xray${reset}"	
				info_xray
				logs_xray_info_xkeen
				info_version_xray
				logs_version_xray_info_xkeen
				
				install_configs
				logs_install_configs_info_xkeen
				
				echo ""
				echo -e "  ${yellow}Проверка${reset} наличия конфигураций"
				logs_install_configs_info_console
				echo -e "  Проверка наличия конфигураций ${green}завершена${reset}"
								
				echo
				echo -e "  ${yellow}Выполняется${reset} обновление регистрации"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset} регистрации"
				
				register_xray_list
				logs_register_xray_list_info_xkeen
				logs_register_xray_list_info_console
				
				register_xray_control
				logs_register_xray_control_info_xkeen
				logs_register_xray_control_info_console
				
				register_xray_status
				logs_register_xray_status_info_xkeen
				logs_register_xray_status_info_console
				
				echo ""
				echo -e "  Проверка регистрации ${green}завершена${reset}"
				
				echo "  Переустановка конфигураций Xray завершена"
            shift
            ;;
			
			
			-x) # Переустановить Xray
				echo "  Переустановка Xray"
				xkeen_info
				
				clear
				echo -e "  ${yellow}Переустановка${reset} Xray"
				backup_configs
				opkg remove xray
				xray_installed="not_installed"

				echo ""
				download_xray
				logs_download_xray_info_xkeen

				install_xray
				xray_installed="installed"

				echo ""
				echo -e "  ${yellow}Установка${reset} конфигурационных файлов Xray"
				mkdir -p "$install_conf_dir" || { echo "Ошибка: Не удалось создать директорию $install_conf_dir"; exit 1; }
				install_configs
				logs_install_configs_info_xkeen

				echo ""
				echo -e "  ${yellow}Проверка${reset} установленных конфигурационных файлов Xray"
				logs_install_configs_info_console
				echo -e "  Проверка установленных конфигурационных файлов Xray ${green}завершена${reset}"

				echo ""
				echo -e "  ${yellow}Обновление${reset} регистрации"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset} регистрации"

				register_xray_list
				logs_register_xray_list_info_xkeen
				logs_register_xray_list_info_console

				register_xray_control
				logs_register_xray_control_info_xkeen
				logs_register_xray_control_info_console

				register_xray_status
				logs_register_xray_status_info_xkeen
				logs_register_xray_status_info_console
				
				register_xray_initd
                                register_autostart
				logs_register_xray_initd_info_xkeen
				logs_register_xray_initd_info_console

				echo ""
				echo -e "  Обновление регистрации ${green}завершено${reset}"

				if input_concordance_list "Хотите включить автоматическое обновление ${yellow}Xray${reset}?"; then
					chose_xray_cron_select=true
				else
					chose_xray_cron_select=false
				fi

				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
					delete_cron_task
					logs_delete_cron_task_info_xkeen

				install_cron
				logs_install_cron_info_xkeen
				logs_install_cron_info_console
				
				restore_backup_configs

				echo -e "  Переустановка Xray ${green}завершена${reset}"	
		
				echo "  Переустановка Xray завершена"	
				shift
				;;

			
		-k)	#Переустановить XKeen
				echo "  Переустановка XKeen"
				xkeen_info
				
				clear
				echo -e "  ${yellow}Переустановка${reset} XKeen"
				echo ""
				download_xkeen
				logs_download_xkeen_info_xkeen
				
				echo ""
				install_xkeen
				
				echo ""
				echo -e "  ${yellow}Обновление${reset} регистрации"
				sleep 1
				echo ""
				echo -e "  ${yellow}Проверка${reset} регистрации"
				
				delete_register_xkeen
				logs_delete_register_xkeen_info_xkeen
														
				register_xkeen_list
				logs_register_xkeen_list_info_xkeen
				logs_register_xkeen_list_info_console
				
				register_xkeen_control
				logs_register_xkeen_control_info_xkeen
				logs_register_xkeen_control_info_console
				
				register_xkeen_status
				logs_register_xkeen_status_info_xkeen
				logs_register_xkeen_status_info_console
				
				register_xray_initd
                                register_autostart
				logs_register_xray_initd_info_xkeen
				logs_register_xray_initd_info_console
				
				echo ""
				echo -e "  Обновление регистрации ${green}завершено${reset}"
				
				if input_concordance_list "Хотите включить автоматическое обновление ${yellow}XKeen?${reset}"; then
                        chose_xkeen_cron_select=true
                    else
                        chose_xkeen_cron_select=false
				fi
				
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
					delete_cron_task
					logs_delete_cron_task_info_xkeen
				
				install_cron
				
				echo -e "  ${Yellow}Проверка${reset} Cron файла на наличие правила автоматического обновления"	
				logs_install_cron_info_xkeen
				logs_install_cron_info_console
				echo -e "  Проверка Cron файла на наличие правила автоматического обновления ${green}завершена${reset}"	
				
				echo ""
				echo -e "  Переустановка XKeen ${green}завершена${reset}"					
								
				delete_tmp
				logs_delete_tmp_info_xkeen
				
				echo "  Переустановка XKeen завершена"				
            shift
            ;;
			
		-xb)	#Сделать резервную копию Xray
				echo "  Создание резервной копии Xray"
				
				info_xray
				logs_xray_info_xkeen
				info_version_xray
				logs_version_xray_info_xkeen
				
				backup_xray				
				
				echo "  Создание резервной копии Xray завершено"
            shift
            ;;
						
		-kb)	#Резервное копирование XKeen
				echo "  Создание резервной копии XKeen"
				
				info_version_xkeen
				logs_version_xkeen_info_xkeen
				
				backup_xkeen		
				
				echo "  Создание резервной копии XKeen завершено"
            shift
            ;;
			
		-cb)	#Сделать резервную конфигураций Xray
				echo "  Создание резервной копии конфигураций Xray"
				
				backup_configs
				
				echo "  Создание резервной копии конфигураций Xray завершено"
            shift
            ;;
						
		-xbr)	# Восстановление резервной копировании Xray
				echo "  Восстановление из резервной копии Xray"
				
				restore_backup_xray
				
				echo "  Восстановление из резервной копии Xray завершено"
            shift
            ;;
			
			
		-kbr)	# Восстановление резервной копировании XKeen
				echo "  Восстановление из резервной копии XKeen"
				
				restore_backup_xkeen	
				
				echo "  Восстановление из резервной копии XKeen завершено"
            shift
            ;;
			
		-cbr)	# Восстановление резервной копировании конфигурационных файлов Xray
				echo "  Восстановление из резервной копии конфигураций Xray"
				
				restore_backup_configs	
				
				echo "  Восстановление из резервной копии конфигураций Xray завершено"
            shift
            ;;
			
						
		-tc)	# Тест соединения
				echo -e "  ${yellow}Проверка${reset} интернет-соединения"
				tests_connection
				echo -e "  Проверка интернет-соединения ${green}завершена${reset}"
				
            shift
            ;;
			
		-tpx)	# Показать прослушиваемые порты
				echo -e "  ${yellow}Проверка${reset} портов Xray"
				tests_ports_xray
				echo -e "  Проверка интернет-соединения ${green}завершена${reset}"
			;;
			
		-tfk)	# Проверить файлы XKeen
				echo -e "  ${yellow}Проверка${reset} файлов XKeen"
				logs_file_check_xkeen_xkeen
				echo -e "  Проверка файлов XKeen ${green}завершена${reset}"
				break
			;;
			
		-tfx)	# Проверить файлы Xray
				echo -e "  ${yellow}Проверка${reset} файлов Xray"
				logs_file_check_xray_xkeen
				echo -e "  Проверка файлов Xray ${green}завершена${reset}"
				break
			;;
						
		-v)	# Показать текущую версию
				info_version_xray
				logs_version_xray_info_xkeen
				echo "  Текущая версия XKeen $xkeen_current_version"
				break
			;;
			
		-ad)	# Можете купить Мне кофе
				author_donate					
            shift
            ;;
			
		-af)	# Обратная связь
				author_feedback			
            shift
            ;;
			
		-start)	# Запуск Xray	
				add_chmod_init
				eval "busybox sh $initd_dir/S24xray start on"
				ip route flush cache
				exit 0
				
            shift
            ;;	
			
		-stop)	# Остановка Xray			
				add_chmod_init
				eval "busybox sh $initd_dir/S24xray stop"
				exit 0
				
            shift
            ;;		
			
		-restart)	# Перезапуск Xray			
				add_chmod_init
				eval "busybox sh $initd_dir/S24xray restart on"
				exit 0
				
            shift
            ;;				
			
		-status)	# Проверка Xray

				eval "busybox sh $initd_dir/S24xray status" 
				
            shift
            ;;		
			
		-auto)  # Переключение значения autostart между "on" и "off"
			if grep -q 'autostart="on"' $initd_dir/S99xkeenstart; then
				sed -i 's/autostart="on"/autostart="off"/' $initd_dir/S99xkeenstart
				echo -e "  Автозапуск XKeen ${red}отключен${reset}"
			else
				sed -i 's/autostart="off"/autostart="on"/' $initd_dir/S99xkeenstart
				echo -e "  Автозапуск XKeen ${green}включен${reset}"
			fi
			exit 0
			add_chmod_init
			
			shift
			;;
			
		-ap)	# Добавить порт Xray
			shift	
				add_ports_donor "$1" 
				sleep 2
				add_chmod_init
				
            shift
            ;;		
			
		-dp)	# Удалить порт Xray
			shift				
				dell_ports_donor "$1"
				sleep 2
				add_chmod_init
				
            shift
            ;;		
			
		-cp) # Получить список портов, на которых работает прокси	
			port_donor=$(grep -m1 '^port_donor=' /opt/etc/init.d/S24xray | cut -d'=' -f2 | tr -d '"' | tr ' ' '\n' | sed 's/^/     /')
				if [ -z "$port_donor" ] || [ "$port_donor" == "     " ]
				then
				  echo -e "  Xray работает ${yellow}на всех${reset} портах"
				else
				  echo -e "  Xray ${green}работает${reset} на портах\n$port_donor"
				fi
				add_chmod_init
			
			shift
            ;;
		-ape)	# Добавить порт-исключение Xray
			shift	
				add_ports_exclude "$1" 
				sleep 2
				add_chmod_init
            shift
            ;;		
			
		-dpe)	# Удалить порт-исключение Xray
			shift				
				dell_ports_exclude "$1"
				sleep 2	
				add_chmod_init
				
            shift
            ;;		
			
		-cpe) # Получить список портов-исключение, на которых не работает прокси	
			port_exclude=$(grep -m1 '^port_exclude=' /opt/etc/init.d/S24xray | cut -d'=' -f2 | tr -d '"' | tr ' ' '\n' | sed 's/^/     /')
				if [ -z "$port_exclude" ] || [ "$port_exclude" == "     " ]
				then
				  echo -e "  ${yellow}Нет портов${reset} Xray для исключения"
				else
				  echo -e "  Xray ${red} не работает${reset} на портах\n$port_exclude"
				fi
				add_chmod_init
			
			shift
            ;;
			
		-modules)	# Переносит модули из прошивки в пользовательскую директорию
				migration_modules
				
            shift
            ;;
			
		-d)		
		shift
			delay_autostart "$1"
			sleep 2	
			add_chmod_init
			
		shift
		;;
			
		-diag)
			diagnostic	
				
			shift
            ;;
					
		-arch)
			archive_xkeen
				
            shift
            ;;
						
		-test)

			shift
            ;;
		
		-fixed)
			entware_fixed
			xkeen_info
			
			backup_configs
			download_xray

			install_xray
			install_configs

			register_xray_list
			register_xray_control
			register_xray_status
			
			register_xray_initd
			register_autostart

			fixed_register_packages
			restore_backup_configs
			
			delete_tmp
			
			shift
            ;;
			
		-h)	#Помощь			
				echo
				echo -e "${light_blue}XKeen${reset} — утилита для обеспечения работы Xray на роутерах Keenetic"
				echo 
				echo -e "	Пример использования"
				echo -e "	xkeen -ap 80,443"
				echo -e "	xkeen	${gray}	Утилита${reset}"
				echo -e "	-ap	${gray}	Выбранный Вами ключ${reset}"
				echo -e "	80,443	${gray}	Аргумент или аргументы ключа через запятую${reset}"
				echo
				echo -e "${yellow}Полный цикл установки${reset}"
				echo -e "	-i	${gray}	Необходимые пакеты, Xray и сервисы XKeen${reset}"
				echo 
				echo -e "${yellow}Обновление${reset}"
				echo -e "	-ug	${gray}	GeoFile${reset}"
				echo -e "	-uk	${gray}	XKeen${reset}"
				echo -e "	-ux	${gray}	Xray${reset}"
				echo 
				echo -e "${yellow}Включение или изменение правил автообновления${reset}"
				echo -e "	-uac	${gray}	GeoFile, XKeen, Xray${reset}"
				echo -e "	-ugc	${gray}	GeoFile${reset}"
				echo -e "	-ukc	${gray}	XKeen${reset}"
				echo -e "	-uxc	${gray}	Xray${reset}"
				echo 
				echo -e "${yellow}Регистрация${reset}"
				echo -e "	-rk	${gray}	XKeen${reset}"
				echo -e "	-rx	${gray}	Xray${reset}"
				echo -e "	-ri	${gray}	Автоматический запуск Xray средствами init.d${reset}"
				echo
				echo -e "${red}Удаление${reset} | Утилиты и компоненты"
				echo -e "	-remove	${gray}	Полная деинсталляция XKeen${reset}"
				echo -e "	-dgs	${gray}	GeoSite${reset}"
				echo -e "	-dgi	${gray}	GeoIP${reset}"
				echo -e "	-dс	${gray}	Конфигурации Xray${reset}"
				echo -e "	-dx	${gray}	Xray${reset}"
				echo -e "	-dt	${gray}	Временные файлы${reset}"
				echo -e "	-dk	${gray}	XKeen${reset}"
				echo 
				echo -e "${red}Удаление${reset} | Автоматические обновления"
				echo -e "	-dac	${gray}	GeoFile, XKeen, Xray${reset}"
				echo -e "	-dgc	${gray}	GeoFile${reset}"
				echo -e "	-dkc	${gray}	XKeen${reset}"
				echo -e "	-dxc	${gray}	Xray${reset}"
				echo
				echo -e "${red}Удаление${reset} | Регистрации"
				echo -e "	-drk	${gray}	XKeen${reset}"
				echo -e "	-drx	${gray}	Xray${reset}"
				echo
				echo -e "${green}Порты${reset} | Через которые будет работать клиент"	
				echo -e "	-ap	${gray}	Добавить${reset}"
				echo -e "	-dp	${gray}	Удалить${reset}"
				echo -e "	-cp	${gray}	Список${reset}"
				echo
				echo -e "${green}Порты${reset} | Которые требуется исключить из работы клиента"
				echo -e "	-ape	${gray}	Добавить${reset}"
				echo -e "	-dpe	${gray}	Удалить${reset}"
				echo -e "	-cpe	${gray}	Список${reset}"
				echo
				echo -e "${green}Обновление регистрации утилит${reset}"
				echo -e "	-rrk	${gray}	XKeen${reset}"
				echo -e "	-rrx	${gray}	Xray${reset}"
				echo
				echo -e "${green}Переустановка${reset}"
				echo -e "	-k	${gray}	XKeen${reset}"
				echo -e "	-x	${gray}	Xray${reset}"
				echo -e "	-rc	${gray}	Конфигурационные файлы Xray${reset}"
				echo
				echo -e "${green}Резервные копии${reset} | Создание"
				echo -e "	-kb	${gray}	XKeen${reset}"
				echo -e "	-xb	${gray}	Xray${reset}"
				echo -e "	-cb	${gray}	Конфигурационные файлов Xray${reset}"
				echo
				echo -e "${green}Резервные копии${reset} | Восстановление последней${reset}"
				echo -e "	-kbr	${gray}	XKeen${reset}"
				echo -e "	-xbr	${gray}	Xray${reset}"
				echo -e "	-cbr	${gray}	Конфигурационные файлы Xray${reset}"
				echo
				echo -e "${light_blue}Проверки${reset}"
				echo -e "	-tpx	${gray}	Порты, шлюз и протокол прокси-клиента${reset}"
				echo -e "	-v	${gray}	Версия XKeen${reset}"
				echo
				echo -e "${light_blue}Управление прокси-клиентом${reset}"
				echo -e "	-start	${gray}	Запуск${reset}"
				echo -e "	-stop	${gray}	Остановка${reset}"
				echo -e "	-restart${gray}	Перезапуск${reset}"
				echo -e "	-status	${gray}	Статус работы${reset}"
				echo -e "	-auto	${gray}	Включить  ${gray}|  Отключить запуск прокси-клиента с роутером${reset}"
				echo -e "	-d	${gray}	Установить начальное время запуска прокси-клиента с роутером${reset}"
				echo -e "	-diag	${gray}	Выполнить диагностику${reset}"
				echo
				echo -e "${light_blue}Управление модулями${reset}"
				echo -e "	-modules ${gray}	Перенос модулей для XKeen в пользовательскую директорию${reset}"
				echo
				echo -e "${light_blue}Автор${reset}"
				echo -e "	-ad	${gray}	Если Вам полезна утилита, можете купить Мне кофе${reset}"
				echo -e "	-af	${gray}	Обратная связь${reset}"
				echo
            shift
            ;;
			
        *)
            echo -e "     Неизвестный ключ: ${red}$1${reset}"
			echo -e "     Список доступных ключей: ${yellow}xkeen -h${reset}"
            shift
            ;;
			
    esac
done
